packages:
  - .

onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - argon2
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - msw
  - protobufjs
