import { randomUUID } from 'node:crypto'
import Tenant from '#modules/tenant/models/tenant'
import User from '#modules/auth/models/user'
import Role from '#modules/permission/models/role'

interface TenantScopedRow {
  tenantId?: string | null
}

/**
 * Ensures tenant-scoped factories do not create throwaway tenants when a test
 * already provided tenantId via merge().
 */
export async function ensureTenantId(row: TenantScopedRow) {
  if (row.tenantId) {
    return row.tenantId
  }

  const id = randomUUID()
  const tenant = await Tenant.create({
    id,
    name: `Test Tenant ${id}`,
    slug: `test-tenant-${id}`,
    status: 'active',
    plan: 'standard',
    rbacVersion: 1,
  })

  row.tenantId = tenant.id
  return tenant.id
}

export async function ensureUserId<Row extends { userId?: string | null }>(row: Row) {
  if (row.userId) {
    return row.userId
  }

  const id = randomUUID()
  const user = await User.create({
    id,
    fullName: `Test User ${id}`,
    email: `user-${id}@example.test`,
    password: 'secret123',
    status: 'active',
  })

  row.userId = user.id
  return user.id
}

export async function ensureRequestedByUserId<Row extends { requestedByUserId?: string | null }>(
  row: Row
) {
  if (row.requestedByUserId) {
    return row.requestedByUserId
  }

  const id = randomUUID()
  const user = await User.create({
    id,
    fullName: `Export User ${id}`,
    email: `export-${id}@example.test`,
    password: 'secret123',
    status: 'active',
  })

  row.requestedByUserId = user.id
  return user.id
}

export async function ensureRoleId<Row extends { roleId?: string | null }>(row: Row) {
  if (row.roleId) {
    return row.roleId
  }

  const id = randomUUID()
  const role = await Role.create({
    id,
    name: `Test Role ${id}`,
    slug: `test-role-${id}`,
    description: 'Generated by factory helper.',
  })

  row.roleId = role.id
  return role.id
}
