import { DateTime } from 'luxon'
import { test } from '@japa/runner'
import governmentCoverageMatrixService from '#modules/integrations/services/government_coverage_matrix_service'
import GovernmentSourceTarget from '#modules/integrations/models/government_source_target'
import SourceDataset from '#modules/integrations/models/source_dataset'
import SourceRecord from '#modules/siop/models/source_record'
import { TenantFactory } from '#database/factories/tenant_factory'

test.group('Government coverage matrix service', () => {
  test('reports UF coverage from primary, DataJud and DJEN operational evidence', async ({
    assert,
  }) => {
    const tenant = await TenantFactory.create()
    const suffix = tenant.id
    const primaryDataset = await createDataset({
      key: `coverage-matrix-primary-${suffix}`,
      source: 'tribunal',
      priority: 'primary',
    })
    const dataJudDataset = await createDataset({
      key: `coverage-matrix-datajud-${suffix}`,
      source: 'datajud',
      priority: 'enrichment',
    })
    const djenDataset = await createDataset({
      key: `coverage-matrix-djen-${suffix}`,
      source: 'djen',
      priority: 'enrichment',
    })
    const primaryTarget = await createTarget({
      sourceDatasetId: primaryDataset.id,
      key: `coverage-matrix:tjac-primary:${suffix}`,
      source: 'tribunal',
      priority: 'primary',
      adapterKey: 'test_tjac_precatorio_sync',
      sourceUrl: 'https://example.test/tjac/precatorios',
      lastDiscoveredCount: 32,
      lastSourceRecordsCount: 4,
    })
    const dataJudTarget = await createTarget({
      sourceDatasetId: dataJudDataset.id,
      key: `coverage-matrix:tjac-datajud:${suffix}`,
      source: 'datajud',
      priority: 'enrichment',
      adapterKey: 'datajud_precatorio_discovery',
      sourceUrl: 'https://api-publica.datajud.cnj.jus.br/api_publica_tjac/_search',
      lastDiscoveredCount: 10,
      lastSourceRecordsCount: 2,
    })
    const djenTarget = await createTarget({
      sourceDatasetId: djenDataset.id,
      key: `coverage-matrix:tjac-djen:${suffix}`,
      source: 'djen',
      priority: 'enrichment',
      adapterKey: 'djen_publication_sync',
      sourceUrl: 'https://comunicaapi.pje.jus.br/api/v1/comunicacao',
      lastDiscoveredCount: 8,
      lastSourceRecordsCount: 1,
    })
    const sourceRecord = await SourceRecord.create({
      tenantId: tenant.id,
      sourceDatasetId: primaryDataset.id,
      source: 'tribunal',
      sourceUrl: 'https://example.test/tjac/precatorios/lista.csv',
      sourceChecksum: `coverage-matrix-${suffix}`,
      originalFilename: 'lista.csv',
      mimeType: 'text/csv',
      fileSizeBytes: 128,
      collectedAt: DateTime.now(),
      rawData: { courtAlias: 'tjac' },
    })

    const matrix = await governmentCoverageMatrixService.build(tenant.id)
    const acre = matrix.states.find((state) => state.stateCode === 'AC')

    assert.equal(matrix.summary.statesCount, 27)
    assert.exists(acre)
    assert.equal(acre?.primary.status, 'validated')
    assert.equal(acre?.primary.targetKey, primaryTarget.key)
    assert.equal(acre?.primary.tenantSourceRecordsCount, 1)
    assert.equal(acre?.datajud.targetKey, dataJudTarget.key)
    assert.equal(acre?.djen.targetKey, djenTarget.key)
    assert.deepEqual(acre?.intelligence, {
      hasPrimaryDiscovery: true,
      hasProcessEnrichment: true,
      hasPublicationSignals: true,
      hasRealDataEvidence: true,
      readyForOperationalScoring: true,
    })
    assert.notInclude(
      matrix.gaps.map((gap) => `${gap.courtAlias}:${gap.code}`),
      'tjac:primary_source_missing'
    )

    await sourceRecord.delete()
    await primaryTarget.delete()
    await dataJudTarget.delete()
    await djenTarget.delete()
    await primaryDataset.delete()
    await dataJudDataset.delete()
    await djenDataset.delete()
    await tenant.delete()
  })
})

async function createDataset(input: {
  key: string
  source: 'tribunal' | 'datajud' | 'djen'
  priority: 'primary' | 'enrichment'
}) {
  return SourceDataset.create({
    key: input.key,
    name: input.key,
    owner: 'Coverage Matrix Test',
    source: input.source,
    federativeLevel: 'state',
    kind: input.source === 'datajud' ? 'public_search_api' : 'tribunal_publication',
    access: 'public',
    priority: input.priority,
    baseUrl: 'https://example.test',
    stateCode: 'AC',
    courtAlias: 'tjac',
    format: input.source === 'datajud' ? 'json' : 'html/csv',
    notes: 'Generated by coverage matrix tests.',
    metadata: { testRun: true },
    isActive: true,
  })
}

async function createTarget(input: {
  sourceDatasetId: string
  key: string
  source: 'tribunal' | 'datajud' | 'djen'
  priority: 'primary' | 'enrichment'
  adapterKey: string
  sourceUrl: string
  lastDiscoveredCount: number
  lastSourceRecordsCount: number
}) {
  return GovernmentSourceTarget.create({
    sourceDatasetId: input.sourceDatasetId,
    key: input.key,
    name: input.key,
    source: input.source,
    federativeLevel: 'state',
    stateCode: 'AC',
    courtAlias: 'tjac',
    branch: 'state_court',
    priority: input.priority,
    adapterKey: input.adapterKey,
    sourceUrl: input.sourceUrl,
    sourceFormat: input.source === 'datajud' ? 'json' : 'html/csv',
    status: 'implemented',
    cadence: 'daily',
    isActive: true,
    lastSuccessAt: DateTime.now(),
    lastDiscoveredCount: input.lastDiscoveredCount,
    lastSourceRecordsCount: input.lastSourceRecordsCount,
    coverageScore: '0.9900',
    metadata: { testRun: true },
  })
}
