import { DateTime } from 'luxon'
import { test } from '@japa/runner'
import GovernmentSourceTarget from '#modules/integrations/models/government_source_target'
import SourceDataset from '#modules/integrations/models/source_dataset'
import tribunalSourceSyncService from '#modules/integrations/services/tribunal_source_sync_service'
import { TenantFactory } from '#database/factories/tenant_factory'

test.group('Tribunal source sync service', () => {
  test('preserves explicit target key order for coverage-prioritized dry runs', async ({
    assert,
  }) => {
    const tenant = await TenantFactory.create()
    const suffix = tenant.id
    const firstDataset = await createDataset(`tribunal-source-sync-order-first-${suffix}`)
    const secondDataset = await createDataset(`tribunal-source-sync-order-second-${suffix}`)
    const firstTarget = await createTarget({
      sourceDatasetId: firstDataset.id,
      key: `tribunal-source-sync-order:first:${suffix}`,
      courtAlias: 'tjac',
    })
    const secondTarget = await createTarget({
      sourceDatasetId: secondDataset.id,
      key: `tribunal-source-sync-order:second:${suffix}`,
      courtAlias: 'tjba',
    })

    const result = await tribunalSourceSyncService.sync({
      tenantId: tenant.id,
      targetKeys: [secondTarget.key, firstTarget.key],
      dryRun: true,
    })
    const dryRunResult = result as {
      targets: Array<{ key: string }>
    }

    assert.deepEqual(
      dryRunResult.targets.map((target) => target.key),
      [secondTarget.key, firstTarget.key]
    )

    await firstTarget.delete()
    await secondTarget.delete()
    await firstDataset.delete()
    await secondDataset.delete()
    await tenant.delete()
  })
})

async function createDataset(key: string) {
  return SourceDataset.create({
    key,
    name: key,
    owner: 'Tribunal Source Sync Test',
    source: 'tribunal',
    federativeLevel: 'state',
    kind: 'tribunal_publication',
    access: 'public',
    priority: 'primary',
    baseUrl: 'https://example.test',
    format: 'html/csv',
    notes: 'Generated by tribunal source sync tests.',
    metadata: { testRun: true },
    isActive: true,
  })
}

async function createTarget(input: { sourceDatasetId: string; key: string; courtAlias: string }) {
  return GovernmentSourceTarget.create({
    sourceDatasetId: input.sourceDatasetId,
    key: input.key,
    name: input.key,
    source: 'tribunal',
    federativeLevel: 'state',
    stateCode: input.courtAlias === 'tjac' ? 'AC' : 'BA',
    courtAlias: input.courtAlias,
    branch: 'state_court',
    priority: 'primary',
    adapterKey: 'generic_tribunal_public_source_sync',
    sourceUrl: 'https://example.test/precatorios',
    sourceFormat: 'html/csv',
    status: 'generic_supported',
    cadence: 'daily',
    isActive: true,
    lastSuccessAt: DateTime.now(),
    coverageScore: '0.9900',
    metadata: { testRun: true },
  })
}
