import { test } from '@japa/runner'
import Permission from '#modules/permission/models/permission'
import RolePermission from '#modules/permission/models/role_permission'
import CessionOpportunity from '#modules/operations/models/cession_opportunity'
import { AssetEventFactory } from '#database/factories/asset_event_factory'
import { DebtorFactory } from '#database/factories/debtor_factory'
import { PrecatorioAssetFactory } from '#database/factories/precatorio_asset_factory'
import { RoleFactory } from '#database/factories/role_factory'
import { TenantFactory } from '#database/factories/tenant_factory'
import { TenantMembershipFactory } from '#database/factories/tenant_membership_factory'
import { UserFactory } from '#database/factories/user_factory'
import { UserRoleFactory } from '#database/factories/user_role_factory'
import type User from '#modules/auth/models/user'
import type Tenant from '#modules/tenant/models/tenant'
import type Role from '#modules/permission/models/role'
import type TenantMembership from '#modules/tenant/models/tenant_membership'
import type UserRole from '#modules/permission/models/user_role'
import type { PermissionSlug } from '#modules/permission/seeders_data'

const BASE_URL = 'http://localhost:3333'

test.group('operations routes', () => {
  test('serves opportunity inbox, pricing, and pipeline movement APIs', async ({ assert }) => {
    const fixture = await createAccessFixture(['operations.read', 'operations.manage'])
    const debtor = await DebtorFactory.merge({
      tenantId: fixture.tenant.id,
      name: 'Instituto Nacional do Seguro Social',
      debtorType: 'autarchy',
      paymentRegime: 'federal_unique',
      paymentReliabilityScore: 96,
    }).create()
    const asset = await PrecatorioAssetFactory.merge({
      tenantId: fixture.tenant.id,
      debtorId: debtor.id,
      nature: 'alimentar',
      lifecycleStatus: 'in_payment',
      faceValue: '5000000.00',
      estimatedUpdatedValue: '5000000.00',
    }).create()
    await AssetEventFactory.merge({
      tenantId: fixture.tenant.id,
      assetId: asset.id,
      eventType: 'payment_available',
      source: 'djen',
      idempotencyKey: 'operations-route-payment-available',
    }).create()
    const sessionCookie = await loginAndGetSessionCookie(fixture.user)
    const csrfToken = await getCsrfToken(sessionCookie, fixture.tenant)

    const list = await apiFetch('/operations/opportunities?grade=A%2B', {
      sessionCookie,
      tenant: fixture.tenant,
    })
    const pricing = await apiFetch(`/operations/opportunities/${asset.id}/pricing`, {
      method: 'POST',
      sessionCookie,
      tenant: fixture.tenant,
      csrfToken,
      body: {
        offerRate: 0.385,
        termMonths: 18,
      },
    })
    const moved = await apiFetch(`/operations/opportunities/${asset.id}/pipeline`, {
      method: 'POST',
      sessionCookie,
      tenant: fixture.tenant,
      csrfToken,
      body: {
        stage: 'offer',
        offerRate: 0.385,
        termMonths: 18,
      },
    })
    const persisted = await CessionOpportunity.query()
      .where('tenant_id', fixture.tenant.id)
      .where('asset_id', asset.id)
      .firstOrFail()

    assert.equal(list.status, 200)
    assert.equal(list.body.meta.total, 1)
    assert.equal(list.body.opportunities[0].asset.id, asset.id)
    assert.equal(pricing.status, 200)
    assert.equal(pricing.body.opportunity.pricing.offerRate, 0.385)
    assert.equal(moved.status, 200)
    assert.equal(moved.body.opportunity.pipeline.stage, 'offer')
    assert.equal(persisted.stage, 'offer')

    await fixture.cleanup()
  })
})

async function createAccessFixture(permissions: PermissionSlug[]) {
  const createdPermissions: Permission[] = []
  const rolePermissions: RolePermission[] = []
  const tenant = await TenantFactory.create()
  const user = await UserFactory.create()
  const role = await RoleFactory.create()
  const membership = await TenantMembershipFactory.merge({
    tenantId: tenant.id,
    userId: user.id,
  }).create()
  const userRole = await UserRoleFactory.merge({
    tenantId: tenant.id,
    userId: user.id,
    roleId: role.id,
  }).create()

  for (const slug of permissions) {
    const existingPermission = await Permission.query().where('slug', slug).first()
    const permission =
      existingPermission ??
      (await Permission.create({
        slug,
        name: slug,
        description: 'Generated by operations route tests.',
      }))

    if (!existingPermission) {
      createdPermissions.push(permission)
    }

    rolePermissions.push(
      await RolePermission.create({
        roleId: role.id,
        permissionId: permission.id,
      })
    )
  }

  return {
    tenant,
    user,
    role,
    async cleanup() {
      await cleanupAccessFixture({
        tenant,
        user,
        role,
        rolePermissions,
        createdPermissions,
        membership,
        userRole,
      })
    },
  }
}

async function cleanupAccessFixture(input: {
  tenant: Tenant
  user: User
  role: Role
  rolePermissions: RolePermission[]
  createdPermissions: Permission[]
  membership: TenantMembership
  userRole: UserRole
}) {
  for (const rolePermission of input.rolePermissions) {
    await rolePermission.delete()
  }

  await input.userRole.delete()
  await input.membership.delete()
  await input.role.delete()
  await input.tenant.delete()
  await input.user.delete()

  for (const permission of input.createdPermissions) {
    await permission.delete()
  }
}

async function loginAndGetSessionCookie(user: User) {
  const loginPage = await fetch(url('/login'), {
    headers: { accept: 'text/html' },
    redirect: 'manual',
  })
  const initialSessionCookie = getCookie(loginPage.headers, 'adonis-session')
  const initialCsrfToken = getCookie(loginPage.headers, 'XSRF-TOKEN')

  if (!initialSessionCookie || !initialCsrfToken) {
    throw new Error('Login page did not issue the expected session and XSRF cookies.')
  }

  const loginResponse = await fetch(url('/login'), {
    method: 'POST',
    redirect: 'manual',
    headers: {
      'accept': 'application/json',
      'content-type': 'application/json',
      'cookie': `adonis-session=${initialSessionCookie}`,
      'x-xsrf-token': xsrfTokenHeader(initialCsrfToken),
    },
    body: JSON.stringify({
      email: user.email,
      password: 'secret123',
    }),
  })

  if (![200, 204, 302, 303].includes(loginResponse.status)) {
    throw new Error(`Login request failed with status ${loginResponse.status}.`)
  }

  return getCookie(loginResponse.headers, 'adonis-session') ?? initialSessionCookie
}

async function getCsrfToken(sessionCookie: string, tenant: Tenant) {
  const response = await fetch(url('/operations/opportunities'), {
    headers: {
      'accept': 'application/json',
      'cookie': `adonis-session=${sessionCookie}`,
      'x-tenant-id': tenant.id,
    },
  })
  const xsrfCookie = getCookie(response.headers, 'XSRF-TOKEN')

  if (!xsrfCookie) {
    throw new Error('XSRF-TOKEN cookie was not issued.')
  }

  return xsrfCookie
}

async function apiFetch(
  path: string,
  options: {
    method?: 'GET' | 'POST'
    sessionCookie: string
    tenant: Tenant
    csrfToken?: string
    body?: Record<string, unknown>
  }
) {
  const headers: Record<string, string> = {
    'accept': 'application/json',
    'content-type': 'application/json',
    'cookie': `adonis-session=${options.sessionCookie}`,
    'x-tenant-id': options.tenant.id,
  }

  if (options.csrfToken) {
    headers['x-xsrf-token'] = xsrfTokenHeader(options.csrfToken)
  }

  const response = await fetch(url(path), {
    method: options.method ?? 'GET',
    headers,
    body: options.body ? JSON.stringify(options.body) : undefined,
  })
  const text = await response.text()

  return {
    status: response.status,
    body: text ? JSON.parse(text) : {},
  }
}

function xsrfTokenHeader(cookieValue: string) {
  return decodeURIComponent(cookieValue)
}

function getCookie(headers: Headers, name: string) {
  const cookies = getSetCookieValues(headers)
  let cookieValue: string | undefined

  for (const cookie of cookies) {
    const match = new RegExp(`(?:^|,\\s*)${name}=([^;]+)`).exec(cookie)

    if (match) {
      cookieValue = match[1]
    }
  }

  return cookieValue
}

function getSetCookieValues(headers: Headers) {
  const getSetCookie = (headers as Headers & { getSetCookie?: () => string[] }).getSetCookie

  if (getSetCookie) {
    return getSetCookie.call(headers)
  }

  const header = headers.get('set-cookie')

  return header ? [header] : []
}

function url(path: string) {
  return `${BASE_URL}${path}`
}
