import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    // Create system tenant for default roles and permissions
    // UUID will be auto-generated by PostgreSQL
    const now = this.now()
    await this.db.table('tenants').insert({
      name: 'System',
      subdomain: 'system',
      plan: 'enterprise',
      is_active: true,
      created_at: now,
      updated_at: now,
    })
  }

  async down() {
    await this.db.from('tenants').where('subdomain', 'system').delete()
  }
}
