import { test } from '@japa/runner'
import AssetFieldEvidence from '#modules/precatorios/models/asset_field_evidence'
import AssetSourceLink from '#modules/precatorios/models/asset_source_link'
import Court from '#modules/reference/models/court'
import ProcessMatchCandidate from '#modules/integrations/models/process_match_candidate'
import SourceDataset from '#modules/integrations/models/source_dataset'
import nationalDataCoherenceService from '#modules/integrations/services/national_data_coherence_service'
import { AssetScoreFactory } from '#database/factories/asset_score_factory'
import { JudicialProcessFactory } from '#database/factories/judicial_process_factory'
import { PrecatorioAssetFactory } from '#database/factories/precatorio_asset_factory'
import { PublicationFactory } from '#database/factories/publication_factory'
import { SourceRecordFactory } from '#database/factories/source_record_factory'
import { TenantFactory } from '#database/factories/tenant_factory'

test.group('National data coherence service', () => {
  test('reports asset completeness and data conflicts by court layer', async ({ assert }) => {
    const tenant = await TenantFactory.create()
    const court = await Court.updateOrCreate(
      { code: `coherence:tjac:${tenant.id}` },
      {
        code: `coherence:tjac:${tenant.id}`,
        alias: 'tjac',
        name: 'Tribunal de Justiça do Acre',
        courtClass: 'state',
      }
    )
    const completeAsset = await PrecatorioAssetFactory.merge({
      tenantId: tenant.id,
      courtId: court.id,
      source: 'tribunal',
      rawData: { courtAlias: 'tjac' },
    }).create()
    const conflictedAsset = await PrecatorioAssetFactory.merge({
      tenantId: tenant.id,
      courtId: court.id,
      source: 'manual',
      rawData: { courtAlias: 'tjac' },
    }).create()
    const dataset = await SourceDataset.create({
      key: `coherence-source-${tenant.id}`,
      name: `coherence-source-${tenant.id}`,
      owner: 'National Data Coherence Test',
      source: 'tribunal',
      federativeLevel: 'state',
      kind: 'tribunal_publication',
      access: 'public',
      priority: 'primary',
      baseUrl: 'https://example.test/tjac',
      stateCode: 'AC',
      courtAlias: 'tjac',
      format: 'csv',
      notes: 'Generated by national data coherence tests.',
      metadata: { testRun: true },
      isActive: true,
    })
    const sourceRecord = await SourceRecordFactory.merge({
      tenantId: tenant.id,
      sourceDatasetId: dataset.id,
      source: 'tribunal',
      sourceChecksum: `coherence-source-record-${tenant.id}`,
    }).create()

    await JudicialProcessFactory.merge({
      tenantId: tenant.id,
      assetId: completeAsset.id,
      source: 'datajud',
      courtAlias: 'tjac',
    }).create()
    await PublicationFactory.merge({
      tenantId: tenant.id,
      assetId: completeAsset.id,
      source: 'djen',
    }).create()
    await AssetScoreFactory.merge({
      tenantId: tenant.id,
      assetId: completeAsset.id,
      finalScore: 91,
      legalSignalScore: 88,
      economicScore: 84,
      liquidityScore: 86,
      riskScore: 77,
      maturityScore: 81,
      dataQualityScore: 93,
    }).create()
    await AssetFieldEvidence.createMany(
      ['cnj_number', 'debtor_name', 'court_alias', 'face_value'].map((fieldKey) => ({
        tenantId: tenant.id,
        assetId: completeAsset.id,
        fieldKey,
        canonicalValue: fieldKey === 'court_alias' ? 'tjac' : `resolved-${fieldKey}`,
        canonicalSource: 'tribunal' as const,
        canonicalSourceRecordId: sourceRecord.id,
        canonicalSourceDatasetId: dataset.id,
        confidence: '0.9500',
        status: 'resolved' as const,
        evidenceCount: 1,
        conflictingValues: [],
        evidence: [{ reason: 'test' }],
      }))
    )
    await AssetSourceLink.create({
      tenantId: tenant.id,
      assetId: conflictedAsset.id,
      sourceRecordId: sourceRecord.id,
      sourceDatasetId: dataset.id,
      linkType: 'conflict',
      confidence: '0.5000',
      matchReason: 'conflicting_court_alias',
      matchedFields: { courtAlias: true },
      normalizedPayload: { courtAlias: 'tjac' },
      rawPointer: { row: 2 },
    })
    await AssetFieldEvidence.create({
      tenantId: tenant.id,
      assetId: conflictedAsset.id,
      fieldKey: 'cnj_number',
      canonicalValue: '0000001-11.2026.8.01.0001',
      canonicalSource: 'tribunal',
      canonicalSourceRecordId: sourceRecord.id,
      canonicalSourceDatasetId: dataset.id,
      confidence: '0.5200',
      status: 'conflict',
      evidenceCount: 2,
      conflictingValues: [{ normalizedValue: '99999999920268010001' }],
      evidence: [{ reason: 'test_conflict' }],
    })
    await ProcessMatchCandidate.create({
      tenantId: tenant.id,
      assetId: conflictedAsset.id,
      sourceRecordId: sourceRecord.id,
      source: 'datajud',
      courtAlias: 'tjac',
      candidateCnj: '0000001-11.2026.8.01.0001',
      candidateDatajudId: `coherence-candidate-${tenant.id}`,
      candidateIndex: 'api_publica_tjac',
      score: 72,
      status: 'ambiguous',
      signals: { reason: 'weak_match' },
      rawData: { testRun: true },
    })

    const report = await nationalDataCoherenceService.build(tenant.id)
    const acre = report.courts.find((item) => item.courtAlias === 'tjac')

    assert.equal(report.summary.totalAssets, 2)
    assert.equal(report.summary.completeAssets, 1)
    assert.equal(report.summary.completeRate, 0.5)
    assert.equal(report.summary.conflictedAssets, 1)
    assert.equal(report.summary.fieldEvidenceConflictAssets, 1)
    assert.equal(report.summary.fieldEvidenceCoverage, 1)
    assert.equal(report.summary.fieldEvidenceResolvedCoverage, 0.5)
    assert.equal(report.summary.pendingCandidateReviewAssets, 1)
    assert.equal(acre?.totalAssets, 2)
    assert.equal(acre?.primarySourceAssets, 1)
    assert.equal(acre?.dataJudProcessAssets, 1)
    assert.equal(acre?.djenPublicationAssets, 1)
    assert.equal(acre?.valuationAssets, 2)
    assert.equal(acre?.scoredAssets, 1)
    assert.equal(acre?.fieldEvidenceAssets, 2)
    assert.equal(acre?.fieldEvidenceResolvedAssets, 1)
    assert.equal(acre?.fieldEvidenceConflictAssets, 1)
    assert.equal(acre?.missing.primarySource, 1)
    assert.equal(acre?.missing.dataJudProcess, 1)
    assert.equal(acre?.missing.djenPublication, 1)
    assert.equal(acre?.missing.score, 1)
    assert.equal(acre?.missing.fieldEvidence, 1)
    assert.equal(acre?.status, 'critical')
    assert.includeMembers(
      report.gaps.filter((gap) => gap.courtAlias === 'tjac').map((gap) => gap.code),
      [
        'missing_primary_source',
        'missing_datajud_process',
        'missing_djen_publication',
        'missing_score',
        'missing_field_evidence',
        'source_conflicts',
        'field_evidence_conflicts',
        'pending_candidate_review',
      ]
    )

    await tenant.delete()
  })
})
