import { test } from '@japa/runner'
import { Bouncer } from '@adonisjs/bouncer'
import * as abilities from '#abilities/main'
import PermissionMiddleware from '#middleware/permission_middleware'
import permissionCacheService from '#shared/services/permission_cache_service'
import Permission from '#modules/permission/models/permission'
import RolePermission from '#modules/permission/models/role_permission'
import type User from '#modules/auth/models/user'
import { RoleFactory } from '#database/factories/role_factory'
import { TenantFactory } from '#database/factories/tenant_factory'
import { TenantMembershipFactory } from '#database/factories/tenant_membership_factory'
import { UserFactory } from '#database/factories/user_factory'
import { UserRoleFactory } from '#database/factories/user_role_factory'
import type { HttpContext } from '@adonisjs/core/http'
import type { PermissionSlug } from '#modules/permission/seeders_data'

test.group('Permission authorization', () => {
  test('allows requests when the active tenant role grants the permission', async ({ assert }) => {
    const fixture = await createPermissionFixture('dashboard.read')
    const response = createResponseRecorder()
    const ctx = createPermissionContext(fixture.user, fixture.tenant.id, response)
    let nextCalled = false

    await new PermissionMiddleware().handle(
      ctx,
      async () => {
        nextCalled = true
      },
      'dashboard.read'
    )

    assert.isTrue(nextCalled)
    assert.equal(response.statusCode, 200)

    await fixture.cleanup()
  })

  test('denies requests when no active tenant role grants the permission', async ({ assert }) => {
    const fixture = await createPermissionFixture('dashboard.read')
    const response = createResponseRecorder()
    const ctx = createPermissionContext(fixture.user, fixture.tenant.id, response)

    await new PermissionMiddleware().handle(
      ctx,
      async () => {
        throw new Error('next should not run')
      },
      'exports.manage'
    )

    assert.equal(response.statusCode, 403)
    assert.equal(response.body.code, 'E_PERMISSION_DENIED')

    await fixture.cleanup()
  })
})

async function createPermissionFixture(permissionSlug: PermissionSlug) {
  permissionCacheService.invalidateAll()

  const tenant = await TenantFactory.create()
  const user = await UserFactory.create()
  const role = await RoleFactory.create()
  const existingPermission = await Permission.query().where('slug', permissionSlug).first()
  const permission =
    existingPermission ??
    (await Permission.create({
      name: permissionSlug,
      slug: permissionSlug,
      description: 'Generated by permission authorization tests.',
    }))
  const membership = await TenantMembershipFactory.merge({
    tenantId: tenant.id,
    userId: user.id,
  }).create()
  const userRole = await UserRoleFactory.merge({
    tenantId: tenant.id,
    userId: user.id,
    roleId: role.id,
  }).create()

  await RolePermission.create({
    roleId: role.id,
    permissionId: permission.id,
  })

  return {
    tenant,
    user,
    async cleanup() {
      permissionCacheService.invalidateAll()
      await userRole.delete()
      await RolePermission.query()
        .where('role_id', role.id)
        .where('permission_id', permission.id)
        .delete()
      await membership.delete()
      if (!existingPermission) {
        await permission.delete()
      }
      await role.delete()
      await tenant.delete()
      await user.delete()
    },
  }
}

function createPermissionContext(
  user: User,
  tenantId: string,
  response: ReturnType<typeof createResponseRecorder>
) {
  return {
    auth: { user },
    tenant: { id: tenantId },
    response,
    bouncer: new Bouncer(() => user, abilities),
  } as unknown as HttpContext
}

function createResponseRecorder() {
  return {
    statusCode: 200,
    body: undefined as any,
    status(statusCode: number) {
      this.statusCode = statusCode
      return this
    },
    send(body: any) {
      this.body = body
      return body
    },
  }
}
